blank_issues_enabled: false
contact_links:
  - name: CrowbarTools Discord
    url: https://discord.gg/tTmMbrG
    about: Use the "[Release] Haven Spotify Integration Overlay" post in the setups channel for discussion, questions, suggestions, and general help.